In [ ]:
# Basic operations in PyTorch

In [14]:
import torch

# Create a 1D tensor
x=torch.tensor([1,2,3,4])
print("1-D array:")
print(x)

# Create a 2D tensor
y=torch.tensor([[1,2,3,4],
               [5,6,7,8]])
print ("2-D array:")
print(y)

# Print shape
print("shape of 1-D array:",x.shape)
print("shape of 2-D array:",y.shape)

# unsqueeze
x_unsqueezed=x.unsqueeze(1)
print("after unsqueezed",x_unsqueezed)
print("after unsqueezed-shape",x_unsqueezed.shape)

# squeeze
x_squeezed = x.squeeze(0)
print("after squeezed",x_squeezed )
print("after squeezed = shape",x_squeezed.shape )

# Check CUDA availability
print("cuda available", torch.cuda.is_available())

1-D array:
tensor([1, 2, 3, 4])
2-D array:
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
shape of 1-D array: torch.Size([4])
shape of 2-D array: torch.Size([2, 4])
after unsqueezed tensor([[1],
        [2],
        [3],
        [4]])
after unsqueezed-shape torch.Size([4, 1])
after squeezed tensor([1, 2, 3, 4])
after squeezed = shape torch.Size([4])
cuda available False


In [16]:
# Autograd experiment

x=torch.tensor(3.0,requires_grad=True)

y=x**3

y.backward()

print(x.grad)


tensor(27.)


In [20]:
# neural network

import torch
import torch.nn as nn
import torch.optim as optim


X=torch.tensor([[1.0],
                [2.0],
                [3.0],
                [4.0],
                [5.0]])

y=torch.tensor([[3.0],
                [5.0],
                [7.0],
                [9.0],
                [11.0]])



In [21]:
# Create a model

model=nn.Linear(1,1)

loss_fn=nn.MSELoss()

optimizer=optim.SGD(model.parameters(),
                    lr=0.01)

In [22]:
# train

for epoch in range(500):

  # f/w pass
  prediction=model(X)

  #Calculate loss
  loss=loss_fn(prediction,y)

  # Clear previous gradients
  optimizer.zero_grad()

  # Autograd calculates gradients
  loss.backward()

  # Update parameters
  optimizer.step()

  if epoch%50==0:
    print(
        f"Epoch {epoch},"
        f"Loss: {loss.item():.6f}"
    )




Epoch 0,Loss: 109.226440
Epoch 50,Loss: 0.001225
Epoch 100,Loss: 0.000873
Epoch 150,Loss: 0.000622
Epoch 200,Loss: 0.000444
Epoch 250,Loss: 0.000316
Epoch 300,Loss: 0.000225
Epoch 350,Loss: 0.000161
Epoch 400,Loss: 0.000114
Epoch 450,Loss: 0.000082


In [23]:
# Inspect starting parametrs

print("Starting weight:", model.weight.item())
print("Starting bias:", model.bias.item())

Starting weight: 1.9950498342514038
Starting bias: 1.0178714990615845


In [24]:
print(model(X))

tensor([[ 3.0129],
        [ 5.0080],
        [ 7.0030],
        [ 8.9981],
        [10.9931]], grad_fn=<AddmmBackward0>)


In [26]:
# test inference to a new value

model.eval()

with torch.no_grad():
    test = torch.tensor([[10.0]])
    prediction = model(test)

print("Prediction for x=10:", prediction.item())

Prediction for x=10: 20.96837043762207
