In [5]:
# Embeddings

import torch
import torch.nn as nn

embedding = nn.Embedding(10, 4)

tokens = torch.tensor([2, 5, 7])

vectors = embedding(tokens)

print(vectors)
print(vectors.shape)

tensor([[ 0.2104, -0.5804,  0.9639, -0.8421],
        [ 1.2115, -1.0686, -0.8759,  0.0111],
        [-1.3052,  0.6949,  1.9509, -1.4787]], grad_fn=<EmbeddingBackward0>)
torch.Size([3, 4])


In [6]:
# Attention Weights

scores = torch.tensor([2.0, 5.0, 1.0])

attention_weights = torch.softmax(scores, dim=0)

print(attention_weights)
print(attention_weights.sum())

tensor([0.0466, 0.9362, 0.0171])
tensor(1.)


In [7]:
# Weighted Values

values = torch.tensor([
    [2.0, 1.0],
    [8.0, 6.0],
    [3.0, 4.0]
])

context = torch.sum(
    attention_weights.unsqueeze(1) * values,
    dim=0
)

print(context)

tensor([7.6346, 5.7326])
